version: "3.8"
services:

  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_DB=${PG_DB}"
    ports:
      - "${PG_PORT}:${PG_PORT}"

  pgadmin:
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
          PGADMIN_DEFAULT_PASSWORD: "test"
      ports:
          - 5050:80
      depends_on:
          - postgres